### PR TITLE
replacing url matches in the target

### PR DESCRIPTION
**Pull request by melalj**
We can replace now url matches on the target

Example:

```
rules: {
  '/posts/([0-9]+)/comments/([0-9]+)': '/posts/$1/comments/$2'
}
```

### CODE REVIEW

**Comment by jifeon** [comment]
@donasaur can you merge it?

**Comment by jifeon** [comment]
@melalj didn't you publish your fork on npm?

**Comment by donasaur** [comment]
Sure, sorry for the delay!

**Comment by jifeon** [comment]
@donasaur I've changed my mind. I tried these changes yesterday and found a bug: if [!pathEndsWithSlash](https://github.com/donasaur/http-proxy-rules/blob/master/index.js#L38) then `match` returns one more pocket and you need to write `$2` instead of `$1` and so on. 

I think this PR was not ready to merge, need:

- [ ] fix the bug described above with something like

```js
for (var i = 1; i < testPrefixMatch.length; i++) {
  target = target.replace('$' + i, testPrefixMatch[i + (pathEndsWithSlash ? 0 : 1)]);
}
``` 

on https://github.com/donasaur/http-proxy-rules/blob/master/index.js#L47

- [ ] add tests
- [ ] add documentation

@melalj can you fix it? or I can do it

**Comment by donasaur** [comment]
@jifeon Sure, either one of you can fix it.

Either way, because of the nature of this change (only replaces strings of the form $i with corresponding matching group), it wasn't really a breaking change and more of a functionality addition (albeit, a buggy one).

**Comment by donasaur** [comment]
@jifeon @melalj Is there an update on fixing this?

**Comment by jifeon** [comment]
@donasaur yep, related task is in current sprint at my work, so will be able to prepare PR soon

**Comment by donasaur** [comment]
@jifeon Following up on this

**Comment by jifeon** [comment]
Sorry for delay, guys. PR is here https://github.com/donasaur/http-proxy-rules/pull/6

**Pull request merged**
